### ISSUE TITLE
Tests Aren't Passing

### ISSUE THREAD

**Issue by dajinchu** [ReGame-VR/WHAM-api#7]
Are the tests supposed to pass right now? I'm trying to figure out if there's something wrong on my side or if we just gotta update the tests.

**Comment by ryan-bradford** [comment]
I updated it (in the last commit) so they all pass on my end.

**Comment by dajinchu** [comment]
Hm. I'm seeing a bunch of them don't finish running, and some don't pass. Are you running tests with `npm test`?

**Comment by dajinchu** [comment]
The DBReseter throws `ER_ROW_IS_REFERENCED: Cannot delete or update a parent row: a foreign key constraint fails` when I run tests.

**Comment by ryan-bradford** [comment]
Yea, I get that error sometimes - I can't figure out why. I always just fix it by manually deleting the tables in the database and then rerunning the tests. But it might point to some larger problem...

**Comment by dajinchu** [comment]
![image](https://user-images.githubusercontent.com/7122182/48397853-1c39fc80-e6ed-11e8-8a8f-fbd8ba83ba39.png)
Still unable to get the tests to pass. The DBTests pass and then a spattering of HTTPTests fail. Seems like all the tests that interact with the database are failing. Maybe the database is set up incorrectly on my machine, but I'm not sure how that would be the case since the webapp works fine when I run it with npm start.

The same tests fail on Travis CI.
Do you run the server before running tests or something?

**Comment by ryan-bradford** [comment]
I remembered that when I was working on another project, I had some problems with the library we are using to hash password ("bcrypt"). It has a bunch of strange dependences to Ruby and non-node.js things. I removed that dependency and replaced it with "bcrypt-nodejs". This might fix your problem...
