### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by dajinchu** [ReGame-VR/WHAM-api#8]
I'm looking into setting up https://travis-ci.org/ so that tests run automatically every time we push to GitHub. If you set up an account there and link your GitHub, you should be able to see the project setup. Travis is nice because it notifies us if the tests fail, and if we use Pull Requests, it will post there to tell us if the pull request breaks our code.

Probably not a requirement to have this, but it's really neat and something that a lot of companies and large open source projects are using to strengthen code quality.

**Comment by ryan-bradford** [comment]
Ooooo having Travis support would be awesome.

**Comment by ryan-bradford** [comment]
Just ran the updated build on Travis. Way more of the tests are passing now. There an issue with date formatting, but the tests actually run this time!

**Comment by dajinchu** [comment]
Yeah the issue was so dumb. The Travis branch was just behind master so the tests didn't have the new register/therapist endpoints
